version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5457:5432"
    env_file:
      - docker/pgsql/pgsql.env
    volumes:
      - db_data:/var/lib/postgresql@14/data:rw
  redis:
    image: redis:latest
    ports:
      - "6400:6379"
    volumes:
      - redis_data:/data
    depends_on:
      - db
volumes:
  db_data:
  redis_data:
