spring:
  datasource:
    url: jdbc:postgresql://localhost:5457/todolist
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8988
springdoc:
  api-docs:
    path: "/swagger-json"